---
# Install and configure Apache web server


- name: install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
  become: yes


- name: configure Apache
  include_tasks: configure.yml
  tags: always


##
# Configure optional modules
##

- name: SSL support
  include_tasks: ssl.yml
  when: "apache_use_ssl|default('yes')|bool"
  tags: always

- name: AzureSSO support
  include_tasks: azuresso.yml
  when: "apache_use_ssl|default('yes')|bool and apache_use_azuresso|default('no')|bool"
  tags: always

- name: CoSign support
  include_tasks: cosign.yml
  when: "apache_use_ssl|default('yes')|bool and apache_use_cosign|default('no')|bool"
  tags: always

- name: WSGI support
  include_tasks: wsgi.yml
  when: "apache_use_wsgi|default('no')|bool"
  tags: always


##
# Virtual hosts
##

- name: Virtual host setup
  include_tasks: virtualhosts.yml
  when: "apache_vhosts|length > 0"
  tags: always


##
# Install redirect files
##

- name: Configure redirects
  ansible.builtin.copy:
    src: "../files/redirects/{{ item.src }}"
    dest: "/etc/apache2/rewrites/{{ item.host }}/{{ item.filename }}"
    owner: "{{ devops_user }}"
    group: "{{ devops_group|default('adm') }}"
    mode: 0664
  loop: "{{ apache_redirect_files }}"
  loop_control:
    label: "{{ item.name|default(item.host+'/'+item.filename) }}"
  notify: reload Apache
  tags:
    - apache_redirects

