---
# Install and configure Apache web server


- name: install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
  become: yes


- name: configure Apache
  include_tasks: configure.yml


##
# Configure optional modules
##

- name: SSL support
  include_tasks: ssl.yml
  when: "apache_use_ssl|default('yes')|bool"

- name: AzureSSO support
  include_tasks: azuresso.yml
  when: "apache_use_ssl|default('yes')|bool and apache_use_azuresso|default('no')|bool"

- name: CoSign support
  include_tasks: cosign.yml
  when: "apache_use_ssl|default('yes')|bool and apache_use_cosign|default('no')|bool"

- name: WSGI support
  include_tasks: wsgi.yml
  when: "apache_use_wsgi|default('no')|bool"


##
# Virtual hosts
##

- name: Virtual host setup
  include_tasks: virtualhosts.yml
  when: "apache_vhosts|length > 0"
  tags:
    - update_certs

