---
# Setup the virtual hosts


##
# DOCUMENT ROOT
##

- name: "Virtual host : docroot : create the directory structure"
  ansible.builtin.file:
    path: "/home/httpd/{{ item.domain }}/{{ item.hostname }}"
    state: directory
    recurse: yes
    owner: "{{ devops_user|default(ansible_user) }}"
    group: "{{ devops_group|default('adm') }}"
    mode: 0775
  become: yes
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.docroot|default('yes')|bool"

- name: "Virtual host : docroot : create the document root"
  ansible.builtin.file:
    path: "/home/httpd/{{ item.domain }}/{{ item.hostname }}/html"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ devops_group|default('adm') }}"
    mode: 0775
  become: yes
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.docroot|default('yes')|bool"



##
# LOGS
##

- name: "Virtual host : logs : create the log directory"
  ansible.builtin.file:
    path: "/var/log/apache2/{{ item.domain }}/{{ item.hostname }}/archive"
    state: directory
    recurse: yes
    owner: root
    group: "{{ devops_group|default('adm') }}"
    mode: 0750
  become: yes
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"

- name: "Virtual host : logs : configure log file rotation"
  ansible.builtin.template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/apache2-{{ item.hostname }}.{{ item.domain }}"
    owner: root
    group: root
    mode: 0644
  vars:
    logs_path: "{{ item.domain }}/{{ item.hostname }}"
  become: yes
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"



##
# REWRITES
##

- name: "Virtual host : rewrites : create the directory structure"
  ansible.builtin.file:
    path: "/etc/apache2/rewrites/{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}/exclusions"
    state: directory
    owner: root
    group: "{{ devops_group|default('adm') }}"
    mode: 0775
  become: yes
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"



##
# APPS
##

- name: "Virtual host : apps : create the directory structure"
  ansible.builtin.file:
    path: "/etc/apache2/apps/{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
    state: directory
    owner: root
    group: "{{ devops_group|default('adm') }}"
    mode: 0775
  become: yes
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"



##
# SSL
##

- name: "Virtual host : ssl : upload the private keys"
  ansible.builtin.copy:
    src: "{{ apache_ssl_certs_path }}{{ item.hostname }}.{{ item.domain }}.key"
    dest: "{{ apache_ssl_privatekeys }}/"
    owner: root
    group: root
    mode: 0400
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: item.use_ssl|default('no')|bool and item.ssl_install_cert|default('yes')|bool
  tags:
    - apache_update_certs

- name: "Virtual host : ssl : upload the certificates"
  ansible.builtin.copy:
    src: "{{ apache_ssl_certs_path }}{{ item.hostname }}.{{ item.domain }}.crt"
    dest: "{{ apache_ssl_path }}/"
    owner: root
    group: root
    mode: 0444
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: item.use_ssl|default('no')|bool and item.ssl_install_cert|default('yes')|bool
  tags:
    - apache_update_certs

### TODO: intermediate certs

- name: "Virtual host : ssl : upload the chain certificates"
  ansible.builtin.copy:
    src: "{{ apache_ssl_certs_path }}{{ item.ssl_chain_cert }}"
    dest: "{{ apache_ssl_path }}/"
    owner: root
    group: root
    mode: 0444
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: item.use_ssl|default('no')|bool and item.ssl_install_cert|default('yes')|bool and item.ssl_chain_cert
  tags:
    - apache_update_certs

- name: "Virtual host : ssl : generate hashed aliases for certificates"
  ansible.builtin.command: "c_rehash {{ apache_ssl_path }}"
  become: yes
  tags:
    - apache_update_certs



##
# VIRTUAL HOST
##

- name: "Virtual host : vhost : create the virtual host conf file"
  ansible.builtin.template:
    src: "{{ item.template|default('virtualhost.j2') }}"
    dest: "/etc/apache2/sites-available/{{ item.priority }}-{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}.conf"
    owner: root
    group: "{{ devops_group|default('adm') }}"
    mode: 0664
  become: yes
  notify: reload Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"

- name: "Virtual host : vhost : enable the virtual host"
  ansible.builtin.shell:
    cmd: "a2ensite {{ item.priority }}-{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
    chdir: "/etc/apache2/sites-available"
    creates: "/etc/apache2/sites-enabled/{{ item.priority }}-{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}.conf"
  become: yes
  notify: reload Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.enable|default('yes')|bool"



##
# PROXYING
##

- name: "Virtual host : proxy : enable proxy module"
  community.general.apache2_module:
    name: proxy
    state: present
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.proxy_origins|default([])|length == 1 or item.plone_site|default('') != ''"

- name: "Virtual host : proxy : enable proxy_http module"
  community.general.apache2_module:
    name: proxy_http
    state: present
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.proxy_origins|default([])|length == 1 or item.plone_site|default('') != ''"

- name: "Virtual host : proxy : enable proxy_balancer module"
  community.general.apache2_module:
    name: proxy_balancer
    state: present
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.proxy_origins|default([])|length > 1"

- name: "Virtual host : proxy : enable lbmethod_byrequests module"
  community.general.apache2_module:
    name: lbmethod_byrequests
    state: present
  become: yes
  notify: restart Apache
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "{{ item.hostname }}.{{ item.domain }}{% if item.use_ssl|default('no')|bool %}-ssl{% endif %}"
  when: "item.proxy_origins|default([])|length > 1"

